name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build-and-release-apk:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y \
              build-essential \
              ccache \
              git \
              libffi-dev \
              libssl-dev \
              python3-dev \
              python3-pip \
              zlib1g-dev
          sudo pip3 install --upgrade cython virtualenv
          git clone https://github.com/kivy/buildozer.git
          cd buildozer
          sudo python3 setup.py install

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
              autoconf \
              automake \
              autotools-dev \
              cmake \
              libtool \
              libsdl2-dev \
              libsdl2-image-dev \
              libsdl2-mixer-dev \
              libsdl2-ttf-dev \
              libjpeg-dev \
              libpng-dev \
              libtiff-dev \
              libwebp-dev \
              openjdk-8-jdk \
              unzip \
              zip

      - name: Build APK
        run: |
          cd /path/to/your/app
          buildozer android clean
          buildozer android debug

